apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-service
  labels:
    hw: "4"
    app: made
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app: predict-service
  template:
    metadata:
      name: predict-service
      labels:
        app: predict-service
    spec:
      containers:
      - name: predict-service
        image: made/inference
        imagePullPolicy: Never # Мы хотим использовать локальный образ, а не тянуть из репозитория.
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8050