data_params:
  input_data_path: "../data/external/heart.csv"
  output_model_path: "../models/model.pkl"
  metric_path: "../models/metrics.json"
  output_predict_path: "../models/predict.csv"
splitting_params:
  test_size: 0.2
  random_state: 3
train_params:
  model_type: "LogisticRegression"