data_params:
  input_data_path: "../data/interim/test.csv"
  output_model_path: "../data/interim/test_model_alt.pkl"
  metric_path: "../data/interim/test_metrics_alt.json"
  output_predict_path: "../data/interim/test_predict.csv"
splitting_params:
  test_size: 0.2
  random_state: 42
train_params:
  model_type: "LogisticRegression"