apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: made-inf-replicaset
  labels:
    hw: "4"
    app: made
spec:
  replicas: 3
  selector:
    matchLabels:
      app: made-inf-replicaset
  template:
    metadata:
      name: made-inf-replicaset
      labels:
        app: made-inf-replicaset
    spec:
      containers:
      - name: made-inf-replicaset
        image: made/inference
        imagePullPolicy: Never # Мы хотим использовать локальный образ, а не тянуть из репозитория.
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8050
