apiVersion: v1
kind: Pod
metadata:
  name: made-inf-probes
  labels:
    hw: "4"
    app: made
spec:
  containers:
  - name: made-inf-probes
    image: made/inference
    imagePullPolicy: Never # Мы хотим использовать локальный образ, а не тянуть из репозитория.
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8050
    readinessProbe:
      httpGet:
        path: /readiness
        port: 8050
      initialDelaySeconds: 15
      periodSeconds: 3
    livenessProbe:
      httpGet:
        path: /liveness
        port: 8050
      initialDelaySeconds: 5
      periodSeconds: 5
  restartPolicy: OnFailure
