apiVersion: apps/v1
kind: Deployment
metadata:
  name: made-inf-replicaset-blue-green
  labels:
    hw: "4"
    app: made
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  selector:
    matchLabels:
      app: made-inf-replicaset-blue-green
  template:
    metadata:
      name: made-inf-replicaset-blue-green
      labels:
        app: made-inf-replicaset-blue-green
    spec:
      containers:
      - name: made-inf-replicaset-blue-green
        image: made/inference
        imagePullPolicy: Never # Мы хотим использовать локальный образ, а не тянуть из репозитория.
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8050
